name: Deploy Cloud Academy

on:
  push:
    branches:
      - main


jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify frontend
        run: |
          npm ci
          npm run lint
          npm run test
          npm run build



      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:

          host: ${{ secrets.EC2_HOST }}

          username: ec2-user

          key: ${{ secrets.EC2_SSH_KEY }}


          script: |

            set -e


            cd ~/cloud_academy


            echo "Updating repository..."

            git fetch origin main

            git reset --hard origin/main


            echo "Installing dependencies..."

            npm ci


            echo "Building application..."

            npm run build


            echo "Deploying files to nginx..."


            sudo rm -rf /usr/share/nginx/html/*


            sudo cp -r frontend/dist/* /usr/share/nginx/html/


            echo "Restarting nginx..."


            sudo systemctl restart nginx


            echo "Deployment completed successfully."
